### PR TITLE
update pom file for deployment to nexus

### PR DESCRIPTION
**Pull request by wei-lee**

### CODE REVIEW

**Comment by wei-lee** [comment]
ping @aliok are these changes ok for deployment to nexus?

**Comment by aliok** [comment]
@wei-lee Maybe we should use this as the parent:
```
<parent>
        <groupId>org.jboss.aerogear</groupId>
        <artifactId>aerogear-parent</artifactId>
        <version>0.2.20.2</version>
    </parent>
```
It is like that in UPS: https://github.com/aerogear/aerogear-unifiedpush-server/blob/master/pom.xml

Having this parent adds some standard stuff, defined in https://github.com/aerogear/aerogear-parent/blob/master/pom.xml

@matzew a quick review?

**Comment by aliok** [comment]
@wei-lee or, leave it like that for now... This is to unblock other work. We can think of a strategy later depending if we want this fork temporary or permanent.

**Comment by wei-lee** [comment]
@aliok ok, will try that

**Pull request merged**
